services:
  stockapp:
    container_name: stock-exchange-app
    image: s1gawron/stock-exchange-app:1.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
      FINNHUB_TOKEN: #Paste free finnhub token here
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    container_name: postgresql
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  redis:
    container_name: redis
    image: redis:7.4.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
